name: Upload new files to Snowflake

on:
  push:
    paths:
      - "data/**"

jobs:
  upload-to-snowflake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Snowflake CLI
        run: |
          pip install --user snowflake-cli
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Configure Snowflake CLI connection
        run: |
          mkdir -p ~/.snowflake
          cat <<EOF > ~/.snowflake/config.toml
          [connections.default]
          account = "${{ secrets.SNOWFLAKE_ACCOUNT }}"
          user = "${{ secrets.SNOWFLAKE_USER }}"
          password = "${{ secrets.SNOWFLAKE_PASSWORD }}"
          role = "${{ secrets.SNOWFLAKE_ROLE }}"
          warehouse = "${{ secrets.SNOWFLAKE_WAREHOUSE }}"
          database = "${{ secrets.SNOWFLAKE_DATABASE }}"
          schema = "${{ secrets.SNOWFLAKE_SCHEMA }}"
          EOF

      - name: Upload new files to internal stage
        run: |
          for file in $(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep "^data/"); do
            echo "Subiendo archivo: $file"
            snowflake file put "$file" @my_internal_stage --auto-compress
          done

      - name: Load files into RAW table
        run: |
          snowflake sql -q "COPY INTO RAW.landing_table FROM @my_internal_stage FILE_FORMAT = (TYPE = 'CSV') PATTERN='.*\.csv' ON_ERROR='CONTINUE'; "
